name: Verify Playlist Submission

on:
  pull_request:
    paths:
      - 'playlist.json'  # Adjust this path if your file is named differently

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema requests
      
      - name: Run verification script
        run: python .github/scripts/verify_playlist.py